### PR TITLE
Compatibility for VS2005-VS2013

### PR DESCRIPTION
**Pull request by CKarper**
snprintf is not on Windows before VS2015, this polyfills it.

### CODE REVIEW

**Comment by rla** [comment]
Thank you! I'm not Windows-native and Travis is not testing there as well, so that's why this has been broken so far. Before merging, would there be an alternative solution to replace the only snprintf call that we have:

```c
snprintf(buf, 1024, "Error on line %d column %d: %s", loc.first, loc.second, e.what());
```

There is sprintf but that does not take max buffer length. Could this be done by taking substring of e.what() and adding necessary length required for other parts? This would limit the total message length so that it fits into the buffer.

**Comment by CKarper** [comment]
I would actually just use a stringstream to build the message.  That should work on all platforms.  I'll rework my PR to work that way.

**Comment by CKarper** [comment]
There you go.   Tested on windows under VS 2013.

**Comment by rla** [comment]
This looks very good, merging.

**Comment by rla** [comment]
Published version 1.5.3 and updated copyright information. Thank you for the pull request!

**Pull request merged**
