### PR TITLE
Add categories to feed items

### PR DESCRIPTION
**Pull request by sdepold**
This PR fixes a rss feed for tests with empty titles and adds categories to feed items.

### CODE REVIEW

**Comment by rla** [comment]
Thank you for pull request. I have merged it into master but before releasing a new version I would like to clarify some things:

 * Categories test uses the Atom namespace declaration for RSS 2 feed, is
   this intentional? RapidXML does not support namespaces, so they are no-op in tests anyway.
 * Can this be trivially extended to extract categories from an RSS 2 channel as well?
   <http://www.rssboard.org/rss-profile#element-channel-category>
 * Supporting Atom entry categories requires something more clever?
   <http://atomenabled.org/developers/syndication/#category>

**Comment by sdepold** [comment]
> Categories test uses the Atom namespace declaration for RSS 2 feed, is this intentional? RapidXML does not support namespaces, so they are no-op in tests anyway.

The test was copied from this issues: https://github.com/sdepold/jquery-rss/issues/62. It's totally possible that it's weird and nothing one would see in the wild.

> Can this be trivially extended to extract categories from an RSS 2 channel as well? http://www.rssboard.org/rss-profile#element-channel-category

I can extend the logic in whichever way you want :) I'm not sure if I understand the link

> Supporting Atom entry categories requires something more clever? http://atomenabled.org/developers/syndication/#category

I can try to tackle this.

**Comment by rla** [comment]
I dropped the namespace from test. I think I have seen it used in the wild to embed Atom in RSS (Wonders of XML!). That would mean you can choose whether you want Atom or RSS (is this ever implemented in a reader?). Anyway, as RapidXML is not supporting namespaces (tags just appear as "namespace:name"), we cannot support this feature without lots of additional code which could potentially make this package slow. There are other parsers that do not make raw performance the main goal and support these fancy things.

About categories:

Looks like there is an inconvenient construct like:

```xml
<category domain="rec.arts.movies.reviews">1983/V</category>
```

Which means we cannot have category as a single string. It needs to be an object with those properties (`domain`) slapped on. This is for both item AND channel categories. The link was documenting the channel category.

Atom category has multiple extra attributes. I propose that we make category an object that contains the following properties:

```javascript
{
    name: String, // RSS 2 text node contents, Atom label attribute,
                          // term attribute when label is missing
    domain: String, // RSS 2 domain
    scheme: String, // Atom scheme attribute
    term: String // Atom term attribute
}
```

With any unset attribute missing and not mix these objects with raw strings (categories without extra attributes). Also, we do no attribute value/semantic validation or pull external XML schemas and stuff. I can release new version as soon as I have categories as objects, then I would not have to break backwards compatibility when someone asks for those extra attributes. Let me know if you plan to work on this. Otherwise I can release new version ASAP with `name` properties only.

**Comment by sdepold** [comment]
If you want to i can make the necessary changes to transform the current
logic to use objects instead of strings. I might be able to add support for
the other stuff later.
Raivo Laanemets <notifications@github.com> schrieb am Sa., 5. Sep. 2015 um
16:34:

**Comment by rla** [comment]
Yeah, that is a good idea.

**Pull request merged**
